import test from 'node:test';
import assert from 'node:assert/strict';
import {createDemoFetcher} from '../lib/vmix-demo.ts';
import {createDashboardService,createVmixService} from '../lib/vmix-proxy.ts';
import {readVmixState} from '../lib/vmix-xml.ts';
import {validateStation,DEFAULT_LAYOUT} from '../lib/stations.ts';
const request=(body:object,origin='http://localhost:3000')=>new Request('http://localhost:3000/api/vmix',{method:'POST',headers:{'Content-Type':'application/json',origin},body:JSON.stringify(body)});
test('demo XML has stable identities and only four available mixes',async()=>{const fetcher=createDemoFetcher(undefined,4);const xml=await (await fetcher('http://demo/api/')).text();const state=readVmixState(xml);assert.equal(state.inputs.length,12);assert.deepEqual(Object.keys(state.active),['1','2','3','4']);assert.equal(state.mixId(2),'demo-mix-2');assert.equal(state.mixId(5),undefined);});
test('demo Cut, timed Fade and Play update shared simulated state',async()=>{let time=0;const fetcher=createDemoFetcher(()=>time,4);const read=async()=>readVmixState(await(await fetcher('http://demo/api/')).text());await fetcher('http://demo/api/?Function=Cut&Input=demo-cam-3&Mix=0');assert.equal((await read()).active[1],'6');await fetcher('http://demo/api/?Function=Fade&Input=demo-video-1&Mix=1&Duration=500');assert.equal((await read()).active[2],'5');time=500;assert.equal((await read()).active[2],'7');await fetcher('http://demo/api/?Function=Play&Input=demo-video-1');assert.match(await(await fetcher('http://demo/api/')).text(),/key="demo-video-1"[^>]*state="Running"/);assert.equal((await fetcher('http://demo/api/?Function=Cut&Input=demo-cam-1&Mix=4')).status,400);});
test('demo dispatch never calls real transport; normal connection remains separate',async()=>{let realCalls=0;let time=0;const demo=createVmixService({fetcher:createDemoFetcher(()=>time,4),now:()=>time,sleep:async ms=>{time+=ms;},cacheMs:0});const handle=createDashboardService(async()=>{realCalls++;return new Response('real');},demo);const command={address:'demo',input:'demo-video-1',mix:2,mixId:'demo-mix-2',play:true,transition:'Fade',duration:500};assert.equal((await handle(request({address:'demo'}))).status,200);assert.equal(((await(await handle(request(command))).json()) as {status:string}).status,'confirmed');const state=readVmixState(await(await handle(request({address:'demo'}))).text());assert.equal(state.active[2],'7');assert.equal(realCalls,0);assert.equal((await handle(request(command,'http://evil.test'))).status,403);assert.equal((await handle(request({...command,mix:5,mixId:'missing'}))).status,409);await handle(request({address:'127.0.0.1:8088'}));assert.equal(realCalls,1);});
test('demo profiles are valid, explicit, and retain target on save',()=>{assert.equal(validateStation({version:1,name:'Demo',address:'demo',mixId:'demo-mix-2',transition:'Cut',duration:500,play:false,layout:DEFAULT_LAYOUT}).address,'demo');});
test('framework request adapters dispatch demo without native Request identity',async()=>{
 const native=request({address:'demo'});
 const adapter={url:native.url,method:native.method,headers:native.headers,clone:()=>native.clone(),text:()=>native.text()} as Request;
 let realCalls=0;
 const handle=createDashboardService(async()=>{realCalls++;return new Response('real');});
 const response=await handle(adapter);
 assert.equal(response.status,200);
 assert.match(await response.text(),/<version>DEMO<\/version>/);
 assert.equal(realCalls,0);
});
test('director preview leaves program untouched and never plays; take swaps buses',async()=>{
 let time=0;const transport=createDemoFetcher(()=>time,4);const commands:string[]=[];
 const service=createDashboardService(undefined,createVmixService({fetcher:(async (url,init)=>{const fn=new URL(String(url)).searchParams.get('Function');if(fn)commands.push(fn);return transport(url,init);}) as typeof fetch,now:()=>time,sleep:async ms=>{time+=ms;},cacheMs:0}));
 const body={address:'demo',input:'demo-video-2',mix:3,mixId:'demo-mix-3',play:true,transition:'Fade',duration:250};
 assert.equal((await service(request({...body,action:'preview'}))).status,200);
 let state=readVmixState(await(await service(request({address:'demo'}))).text());
 assert.equal(state.active[3],'6');assert.equal(state.preview[3],'8');assert.deepEqual(commands,['PreviewInput']);
 assert.equal((await service(request({...body,action:'take'}))).status,200);
 state=readVmixState(await(await service(request({address:'demo'}))).text());
 assert.equal(state.active[3],'8');assert.equal(state.preview[3],'6');assert.deepEqual(commands,['PreviewInput','Fade','Play']);
 const before=commands.length;
 assert.equal((await service(request({...body,action:'take'}))).status,409);
 assert.equal((await service(request({...body,action:'bad'}))).status,400);
 assert.equal(commands.length,before);
});
test('main and additional previews are parsed independently',async()=>{
 const state=readVmixState(await(await createDemoFetcher(undefined,4)('http://demo/api/')).text());
 assert.equal(state.preview[1],'5');assert.equal(state.preview[2],'4');assert.equal(state.preview[3],'7');assert.equal(state.preview[4],'8');
});
test('operators discover and join the local connection; cannot select their own target',async()=>{
 let realCalls=0;const real=async()=>{realCalls++;return new Response('<vmix/>');};
 const service=createDashboardService(real,createVmixService({fetcher:createDemoFetcher(),cacheMs:0}),r=>r.headers.get('x-test-local')==='yes');
 const get=()=>service(new Request('http://localhost:3000/api/vmix'));
 assert.deepEqual(await(await get()).json(),{address:null});
 assert.equal((await service(request({address:'demo'}))).status,409);
 const local=(body:object)=>{const r=request(body);r.headers.set('x-test-local','yes');return r;};
 assert.equal((await service(local({address:'demo',connect:true}))).status,200);
 assert.deepEqual(await(await get()).json(),{address:'demo'});
 const guest=await service(request({address:'192.168.0.1:8088'}));assert.equal(guest.status,200);assert.match(await guest.text(),/<version>DEMO<\/version>/);assert.equal(realCalls,0);
 assert.equal((await service(request({address:'192.168.0.1:8088',connect:true}))).status,403);
 assert.equal(realCalls,0);
 assert.equal((await service(request({address:'different',input:'demo-cam-1'}))).status,409);
 assert.equal((await service(local({address:'127.0.0.1:8088',connect:true}))).status,200);
 await service(local({address:'demo'}));assert.deepEqual(await(await get()).json(),{address:'127.0.0.1:8088'});
 assert.equal((await service(request({disconnect:true}))).status,403);
 assert.equal((await service(local({disconnect:true}))).status,200);
 assert.deepEqual(await(await get()).json(),{address:null});
});
