'use client';
import {createContext,useContext,useEffect,useRef,useState,type ReactNode} from 'react';
import {LockKeyhole,Radio,LogOut} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
import {useLanguage} from '@/components/language-provider';
import './access-control.css';
type Status={enabled:boolean;authenticated:boolean;local:boolean;operatorName?:string};
const AccessContext=createContext({local:false,operatorName:''});
export const useAccess=()=>useContext(AccessContext);
async function status():Promise<Status>{const response=await fetch('/api/access',{cache:'no-store'});if(!response.ok)throw Error('Access configuration unavailable');return response.json() as Promise<Status>;}
async function action(body:object,announce=true){const response=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||'Access configuration unavailable');if(announce)window.dispatchEvent(new Event('vmix-access-changed'));}
export function AccessGate({children}:{children:ReactNode}){
 const {t}=useLanguage();const [access,setAccess]=useState<Status|null>(null),[operatorName,setOperatorName]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{try{setOperatorName(localStorage.getItem('vmix-operator-name')||'');}catch{}},[]);
 useEffect(()=>{let stopped=false;async function check(){try{const value=await status();if(!stopped)setAccess(value);}catch{if(!stopped){setAccess(null);setError('Access configuration unavailable');}}}void check();const timer=setInterval(check,5000);window.addEventListener('vmix-access-changed',check);return()=>{stopped=true;clearInterval(timer);window.removeEventListener('vmix-access-changed',check);};},[]);
 if(access?.authenticated)return <AccessContext.Provider value={{local:access.local,operatorName:access.operatorName||operatorName}}>{children}</AccessContext.Provider>;
 return <div className="access-screen"><form className="access-card" onSubmit={async e=>{e.preventDefault();if(busy||!access)return;const name=operatorName.trim();if(!name||operatorName.length>80){setError('Enter an operator name (1–80 characters)');return;}setBusy(true);setError('');try{await action({action:'login',password,operatorName:name},false);setOperatorName(name);try{localStorage.setItem('vmix-operator-name',name);}catch{}setPassword('');setAccess(await status());}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><div className="access-brand"><Radio size={24}/><span>vMix Control</span></div><LockKeyhole className="access-lock" size={28}/><h1>{t('Password required')}</h1>{access&&<><div className="access-login-field"><label htmlFor="access-operator-name">{t('Operator name')}</label><Input id="access-operator-name" name="username" type="text" autoComplete="username" autoFocus required maxLength={80} value={operatorName} disabled={busy} onChange={e=>{setOperatorName(e.target.value);setError('');}}/></div><div className="access-login-field"><label htmlFor="access-password">{t('Password')}</label><Input id="access-password" type="password" name="password" autoComplete="current-password" required value={password} maxLength={128} disabled={busy} onChange={e=>setPassword(e.target.value)}/></div><Button type="submit" disabled={busy||!password||!operatorName.trim()}>{t(busy?'Please wait':'Unlock dashboard')}</Button></>}{error&&<p role="alert">{t(error)}</p>}{!access&&!error&&<p role="status">{t('Please wait')}</p>}</form></div>;
}
export function AccessSettings(){
 const passwordRef=useRef<HTMLInputElement>(null);
 const {t}=useLanguage();const [enabled,setEnabled]=useState(false),[desired,setDesired]=useState(false),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[current,setCurrent]=useState(''),[busy,setBusy]=useState(false),[ready,setReady]=useState(false),[local,setLocal]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 useEffect(()=>{let stopped=false;void status().then(value=>{if(!stopped){setEnabled(value.enabled);setDesired(value.enabled);setLocal(value.local);setReady(true);}}).catch(()=>{if(!stopped)setError('Access configuration unavailable');});return()=>{stopped=true;};},[]);
 async function save(){if(busy||!ready)return;setSaved(false);setError('');if(enabled&&!local&&!current){setError('Password required');return;}if(desired&&(password.length<4||password.length>128)){setError('Use 4–128 characters');passwordRef.current?.focus();return;}if(desired&&password!==confirm){setError('Passwords do not match');return;}setBusy(true);try{await action({action:'configure',enabled:desired,password,currentPassword:current});setEnabled(desired);setPassword('');setConfirm('');setCurrent('');setSaved(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(ready&&!local)return enabled?<div className="access-settings"><Button type="button" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await action({action:'logout'});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><LogOut size={14}/>{t('Log out')}</Button>{error&&<p className="access-error" role="alert">{t(error)}</p>}</div>:null;
 return <section className="access-settings"><div className="settings-play-row"><label htmlFor="password-protection">{t('Password protection')}</label><Switch id="password-protection" checked={desired} disabled={busy||!ready} onCheckedChange={value=>{setDesired(value);setSaved(false);setError('');}}/></div>{(desired||enabled)&&<div className="access-fields">{enabled&&!local&&<label>{t('Current password')}<Input type="password" autoComplete="current-password" value={current} maxLength={128} disabled={busy} onChange={e=>{setCurrent(e.target.value);setSaved(false);}}/></label>}{desired&&<><div className="access-password-field"><label htmlFor="new-access-password">{t('New password')}</label><div className="password-input-wrap">{error==='Use 4–128 characters'&&<span id="new-password-error" className="password-error-bubble" role="alert">{t(error)}</span>}<Input ref={passwordRef} id="new-access-password" type="password" autoComplete="new-password" aria-describedby={error==='Use 4–128 characters'?'new-password-error':undefined} aria-invalid={error==='Use 4–128 characters'} value={password} minLength={4} maxLength={128} disabled={busy} onChange={e=>{setPassword(e.target.value);setSaved(false);setError('');}}/></div></div><label>{t('Confirm password')}<Input type="password" autoComplete="new-password" value={confirm} maxLength={128} disabled={busy} onChange={e=>{setConfirm(e.target.value);setSaved(false);setError('');}}/></label></>}<div className="access-actions"><Button type="button" disabled={busy||!ready} onClick={()=>void save()}>{t('Save access settings')}</Button>{enabled&&!local&&<Button type="button" variant="outline" disabled={busy} onClick={async()=>{setBusy(true);try{await action({action:'logout'});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><LogOut size={14}/>{t('Log out')}</Button>}</div></div>}{saved&&<p className="access-saved" role="status">{t('Access settings saved')}</p>}{error&&error!=='Use 4–128 characters'&&<p className="access-error" role="alert">{t(error)}</p>}</section>;
}
