'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {shortcutAction} from '@/lib/switcher-shortcuts';
import {inputPage,INPUT_PAGE_SIZES} from '@/lib/input-pages';
import {useLanguage} from '@/components/language-provider';
import './director-panel.css';
import {Radio,Eye,ArrowRight,LoaderCircle,ChevronLeft,ChevronRight,LocateFixed} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {TRANSITIONS,hasDuration} from '@/lib/transitions';
import type {Source} from '@/lib/vmix-state';
type Props={overlayControls?:ReactNode;shortcuts:boolean;inputs:Source[];allInputs:Source[];program:string;preview:string;mixId:string;online:boolean;busy:boolean;demo:boolean;transition:string;duration:string;durationValid:boolean;onTransition:(effect:string,duration:string)=>void;onPreview:(input:Source)=>void;onProgram:(input:Source)=>void;onTake:(effect:string)=>void};
export function DirectorPanel(p:Props){
 const {t}=useLanguage();
 const [pageSize,setPageSize]=useState(12);
 const [selection,setSelection]=useState({scope:'',page:0});
 const scope=JSON.stringify([p.mixId,pageSize,p.inputs.map(i=>i.key)]);
 const bank=inputPage(p.inputs,selection.scope===scope?selection.page:0,pageSize);
 function selectPage(page:number){setSelection({scope,page});}
 function sourcePage(source:Source|undefined){const index=p.inputs.findIndex(i=>i.key===source?.key);return index<0?-1:Math.floor(index/pageSize);}
 const find=(value:string)=>p.allInputs.find(i=>i.number===value||i.key===value);
 const program=find(p.program),preview=find(p.preview),locked=!p.online||p.busy;
 const canTake=!locked&&!!preview&&preview.key!==p.mixId&&preview.key!==program?.key;
 const auto=p.transition==='Cut'?'Fade':p.transition;
 const autoValid=!hasDuration(auto)||(/^\d+$/.test(p.duration)&&Number(p.duration)>=1&&Number(p.duration)<=10000);
 useEffect(()=>{function handle(event:KeyboardEvent){const target=event.target instanceof Element?event.target:null;const blocked=!p.shortcuts||locked||event.defaultPrevented||!!document.querySelector('[role="dialog"], [role="menu"], [role="listbox"]')||!!target?.closest('input,textarea,select,[contenteditable]:not([contenteditable="false"]),[role="textbox"],[role="combobox"]');const action=shortcutAction(event,blocked,!!target?.closest('button,[role="button"],a'));if(!action)return;if(action.kind==='preview'){const input=bank.items[action.index];if(!input||input.key===p.mixId)return;event.preventDefault();p.onPreview(input);}else if(canTake&&(action.effect==='cut'||autoValid)){event.preventDefault();p.onTake(action.effect==='cut'?'Cut':auto);}}window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);});
 return <div className="director-desk"><div className="director-buses"><div className="bus-readouts">
 {[{name:'PROGRAM',source:program,kind:'program',Icon:Radio},{name:'PREVIEW',source:preview,kind:'preview',Icon:Eye}].map(({name,source,kind,Icon})=><div key={kind} className={`bus-readout bus-${kind} ${!p.online?'bus-offline':''}`}><div className="bus-readout-label"><Icon size={15}/>{name}<span>{p.demo?'DEMO':p.online?'VMIX':'OFFLINE'}</span></div><strong title={source?.title}>{source?.title||'—'}</strong><small>{source?`INPUT ${source.number.padStart(2,'0')}`:t("Wybierz źródło")}</small>{sourcePage(source)>=0&&sourcePage(source)!==bank.page&&<Button variant="ghost" className="bus-locate" disabled={p.busy} aria-label={t('Pokaż na stronie')} title={t('Pokaż na stronie')} onClick={()=>selectPage(sourcePage(source))}><LocateFixed size={14}/></Button>}</div>)}
 </div>{(p.inputs.length>12||pageSize!==12)&&<nav className="bus-pagination" aria-label={t('Strony inputów')}><span className="bus-page-range">{p.inputs.length?bank.start+1:0}–{bank.end}<span> / {p.inputs.length}</span></span><div className="bus-page-actions"><NativeSelect aria-label={t('Inputy na stronę')} value={String(pageSize)} disabled={p.busy} onChange={e=>setPageSize(Number(e.target.value))}>{INPUT_PAGE_SIZES.map(size=><NativeSelectOption key={size} value={String(size)}>{t('{count} na stronę',{count:size})}</NativeSelectOption>)}</NativeSelect><Button variant="outline" disabled={p.busy||bank.page===0} aria-label={t('Poprzednia strona')} onClick={()=>selectPage(bank.page-1)}><ChevronLeft size={15}/></Button><span className="bus-page-count" role="status">{bank.page+1} / {bank.pages}</span><Button variant="outline" disabled={p.busy||bank.page>=bank.pages-1} aria-label={t('Następna strona')} onClick={()=>selectPage(bank.page+1)}><ChevronRight size={15}/></Button></div></nav>}<div className="bus-bank"><div className="bus-bank-label"><span className="bus-dot program-dot"/>PROGRAM <small>{t("Bezpośredni CUT")}</small></div><div className="bus-keys">{bank.items.map(input=><Button variant="outline" key={input.key} title={input.title} className={`switcher-key ${p.online&&program?.key===input.key?'key-program':''}`} disabled={locked||input.key===p.mixId} aria-label={t("PROGRAM: {name}, natychmiastowy CUT",{name:input.title})} aria-pressed={p.online&&program?.key===input.key} onClick={()=>p.onProgram(input)}><span className="key-index">{input.number.padStart(2,'0')}</span><span className="key-title">{input.title}</span><span className="key-type">{input.type}</span></Button>)}</div></div>
 <div className="bus-bank"><div className="bus-bank-label"><span className="bus-dot preview-dot"/>PREVIEW <small>{t("Wybór podglądu")}</small></div><div className="bus-keys">{bank.items.map(input=><Button variant="outline" key={input.key} title={input.title} className={`switcher-key ${p.online&&preview?.key===input.key?'key-preview':''}`} disabled={locked||input.key===p.mixId} aria-label={`PREVIEW: ${input.title}`} aria-pressed={p.online&&preview?.key===input.key} onClick={()=>p.onPreview(input)}><span className="key-index">{input.number.padStart(2,'0')}</span><span className="key-title">{input.title}</span><span className="key-type">{input.type}</span></Button>)}</div></div></div>
 <aside className="director-transition" aria-label={t("Przejście na program")}><div className="desk-caption">{t("PRZEJŚCIE")}</div><div className="desk-effects">{['Fade','Wipe','Zoom','Merge'].map(effect=><Button key={effect} variant="outline" disabled={locked} aria-pressed={auto===effect} onClick={()=>p.onTransition(effect,p.duration)}>{effect==='Fade'?'MIX':effect.toUpperCase()}</Button>)}</div><NativeSelect aria-label={t("Efekt AUTO")} value={auto} disabled={locked} onChange={e=>p.onTransition(e.target.value,p.duration)}>{TRANSITIONS.filter(e=>e!=='Cut').map(e=><NativeSelectOption key={e} value={e}>{e}</NativeSelectOption>)}</NativeSelect><label className="desk-duration" htmlFor="director-duration"><span>{t("Czas")} <small>ms</small></span><Input id="director-duration" type="number" min={1} max={10000} value={p.duration} disabled={locked||!hasDuration(auto)} aria-invalid={!autoValid} onChange={e=>p.onTransition(auto,e.target.value)}/></label><div className="desk-times">{[250,500,1000].map(ms=><Button variant="ghost" key={ms} disabled={locked||!hasDuration(auto)} aria-pressed={Number(p.duration)===ms&&hasDuration(auto)} onClick={()=>p.onTransition(auto,String(ms))}>{ms}</Button>)}</div>{!autoValid&&<p className="desk-validation" role="alert">{t("Czas: 1–10000 ms")}</p>}{p.overlayControls}<div className="desk-take-target"><Eye size={14}/><span>{preview?.title||t("Brak podglądu")}</span><ArrowRight size={14}/><Radio size={14}/></div><div className="desk-take-buttons"><Button variant="outline" className="take-cut" disabled={!canTake} onClick={()=>p.onTake('Cut')}>CUT</Button><Button variant="outline" className="take-auto" disabled={!canTake||!autoValid} onClick={()=>p.onTake(auto)}>AUTO</Button></div>{p.shortcuts&&<div className="shortcut-hint">1–9 / 0 / − / = → PREVIEW<br/>Enter → AUTO · C → CUT</div>}<div role="status" className="desk-state">{p.busy?<><LoaderCircle size={14} className="desk-spinner"/>{t("Potwierdzanie…")}</>:!p.online?t("Brak połączenia"):preview?.key===program?.key?'PREVIEW = PROGRAM':<><span className="bus-dot preview-dot"/>{t("Gotowy")}</>}</div></aside></div>;
}
