'use client';
import {useLanguage} from '@/components/language-provider';
import {ProfileManager} from '@/components/profile-manager';
import {selectedProfile} from '@/lib/station-session';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Switch} from '@/components/ui/switch';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Star,ArrowUp,ArrowDown,GripVertical} from 'lucide-react';
import {reorderInputs} from '@/lib/reorder-inputs';
import {editItems,type Layout,type Station} from '@/lib/stations';
export function StationPanel({operatorName,operatorNameReadOnly=false,onOperatorName,name,setName,profiles,onProfilesChange,onRename,onLoad,onSave,onShare,link,layout,onLayout,inputs,disabled,canSave}:{operatorName:string;operatorNameReadOnly?:boolean;onOperatorName:(value:string)=>void;name:string;setName:(s:string)=>void;profiles:Station[];onProfilesChange:(p:Station[])=>void;onRename:(old:string,next:string)=>void;onLoad:(p:Station)=>void;onSave:()=>void;onShare:()=>void;link:string;layout:Layout;onLayout:(l:Layout)=>void;inputs:{key:string;title:string}[];disabled:boolean;canSave:boolean}){
 const {t}=useLanguage();
 const [editing,setEditing]=useState(false);
 const [manager,setManager]=useState(false);
 const drag=useRef('');const [dragging,setDragging]=useState('');
 const items=editItems(inputs,layout);
 function patch(index:number,change:Partial<typeof items[number]>){onLayout({...layout,items:items.map((item,i)=>i===index?{...item,...change}:item)});}
 function move(index:number,offset:number){const next=[...items];[next[index],next[index+offset]]=[next[index+offset],next[index]];onLayout({...layout,items:next});}
 return <section className="station-panel"><div className="station-toolbar"><div className="operator-name"><label htmlFor="operator-name">{t("Operator")}</label><Input id="operator-name" readOnly={operatorNameReadOnly} value={operatorName} onChange={e=>onOperatorName(e.target.value)} maxLength={80} disabled={disabled}/></div><div className="station-name"><label htmlFor="station-name">{t("Stanowisko")}</label><Input id="station-name" placeholder={t("np. Wóz 1 — grafika")} value={name} maxLength={80} onChange={e=>setName(e.target.value)} disabled={disabled}/></div><NativeSelect aria-label={t("Wczytaj zapisane stanowisko")} value="" onChange={e=>{const p=selectedProfile(profiles,e.target.value);if(p)onLoad(p);}} disabled={disabled}><NativeSelectOption value="">{t("Wczytaj profil…")}</NativeSelectOption>{profiles.map((p,i)=><NativeSelectOption key={i} value={String(i)}>{p.name}</NativeSelectOption>)}</NativeSelect><Button variant="outline" disabled={disabled||!canSave||!name.trim()} onClick={onSave}>{t("Zapisz profil")}</Button><Button variant="outline" disabled={disabled||!canSave||!name.trim()} onClick={onShare}>{t("Link stanowiska")}</Button><Button variant="outline" aria-expanded={manager} onClick={()=>setManager(!manager)}>{t("Profile")}</Button><Button variant="outline" disabled={disabled||!inputs.length} aria-expanded={editing} aria-controls="station-input-editor" onClick={()=>setEditing(!editing)}>{t("Układ inputów")}</Button></div>
 {manager&&<ProfileManager profiles={profiles} onChange={onProfilesChange} onRename={onRename} disabled={disabled}/>}
 {link&&<div className="station-link"><label htmlFor="station-link">{t("Link zawiera kopię bieżącego profilu. Otwórz go na urządzeniu operatora.")}</label><Input id="station-link" readOnly value={link} onFocus={e=>e.target.select()}/><p>{t("Udostępniając link, używaj adresu LAN dashboardu zamiast localhost.")}</p></div>}
 <div id="station-input-editor" hidden={!editing} className="station-editor"><div className="editor-heading"><p>{t("Zmień widoczność, oznacz ulubione i wpisz nazwy grup. Strzałki zmieniają kolejność wewnątrz grup.")}</p><label className="new-source-switch"><Switch checked={layout.showNew} onCheckedChange={value=>onLayout({...layout,items,showNew:value})} disabled={disabled}/>{t("Pokazuj nowo dodane inputy")}</label></div>{items.map((item,index)=>{const source=inputs.find(i=>i.key===item.key);return <div className={`editor-row ${dragging===item.key?'is-dragging':''}`} key={item.key} onDragOver={e=>{if(!disabled&&drag.current){e.preventDefault();e.dataTransfer.dropEffect='move';}}} onDrop={e=>{if(disabled||!drag.current)return;e.preventDefault();onLayout({...layout,items:reorderInputs(items,drag.current,item.key)});drag.current='';setDragging('');}}><Button variant="ghost" className="drag-handle" disabled={disabled} draggable={!disabled} aria-label={t('Przeciągnij input')} title={t('Przeciągnij input')} onDragStart={e=>{drag.current=item.key;setDragging(item.key);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',item.key);}} onDragEnd={()=>{drag.current='';setDragging('');}}><GripVertical size={16}/></Button><Switch aria-label={t("Pokaż {name}",{name:source?.title||t('niedostępny input')})} checked={item.visible} disabled={disabled} onCheckedChange={value=>patch(index,{visible:value})}/><span>{source?.title||t("Input obecnie niedostępny")}</span><Button variant="ghost" aria-label={t("Ulubiony: {name}",{name:source?.title||item.key})} aria-pressed={item.favorite} disabled={disabled} onClick={()=>patch(index,{favorite:!item.favorite})}><Star size={17} fill={item.favorite?'currentColor':'none'}/></Button><Input aria-label={t("Grupa dla {name}",{name:source?.title||item.key})} placeholder={t("Grupa, np. Plansze")} value={item.group} maxLength={40} disabled={disabled} onChange={e=>patch(index,{group:e.target.value})}/><Button variant="outline" aria-label={t("Przesuń {name} w górę",{name:source?.title||item.key})} disabled={disabled||index===0} onClick={()=>move(index,-1)}><ArrowUp size={16}/></Button><Button variant="outline" aria-label={t("Przesuń {name} w dół",{name:source?.title||item.key})} disabled={disabled||index===items.length-1} onClick={()=>move(index,1)}><ArrowDown size={16}/></Button></div>;})}<p>{t("Bieżące ustawienia zapisują się lokalnie. „Zapisz profil” zachowuje osobny preset.")}</p></div></section>;
}
