export const accessRows=`Password protection|Ochrona hasłem|Passwortschutz|Protection par mot de passe|Protección con contraseña|Protecție prin parolă|Защита паролем|Protezione con password|Proteção por senha|Захист паролем
Password required|Wymagane hasło|Passwort erforderlich|Mot de passe requis|Contraseña requerida|Parolă necesară|Требуется пароль|Password richiesta|Senha necessária|Потрібен пароль
Password|Hasło|Passwort|Mot de passe|Contraseña|Parolă|Пароль|Password|Senha|Пароль
Current password|Obecne hasło|Aktuelles Passwort|Mot de passe actuel|Contraseña actual|Parola actuală|Текущий пароль|Password attuale|Senha atual|Поточний пароль
New password|Nowe hasło|Neues Passwort|Nouveau mot de passe|Nueva contraseña|Parolă nouă|Новый пароль|Nuova password|Nova senha|Новий пароль
Confirm password|Powtórz hasło|Passwort bestätigen|Confirmer le mot de passe|Confirmar contraseña|Confirmă parola|Повторите пароль|Conferma password|Confirmar senha|Повторіть пароль
Unlock dashboard|Otwórz panel|Dashboard entsperren|Déverrouiller le panneau|Desbloquear panel|Deblochează panoul|Открыть панель|Sblocca pannello|Desbloquear painel|Відкрити панель
Save access settings|Zapisz ustawienia dostępu|Zugriffseinstellungen speichern|Enregistrer les accès|Guardar ajustes de acceso|Salvează accesul|Сохранить настройки доступа|Salva impostazioni accesso|Salvar configurações de acesso|Зберегти налаштування доступу
Log out|Wyloguj|Abmelden|Déconnexion|Cerrar sesión|Deconectare|Выйти|Esci|Sair|Вийти
Access settings saved|Zapisano ustawienia dostępu|Zugriffseinstellungen gespeichert|Paramètres enregistrés|Ajustes guardados|Setări salvate|Настройки сохранены|Impostazioni salvate|Configurações salvas|Налаштування збережено
Passwords do not match|Hasła nie są identyczne|Passwörter stimmen nicht überein|Les mots de passe diffèrent|Las contraseñas no coinciden|Parolele nu coincid|Пароли не совпадают|Le password non coincidono|As senhas não coincidem|Паролі не збігаються
Incorrect password|Nieprawidłowe hasło|Falsches Passwort|Mot de passe incorrect|Contraseña incorrecta|Parolă incorectă|Неверный пароль|Password errata|Senha incorreta|Неправильний пароль
Use 4–128 characters|Użyj 4–128 znaków|4–128 Zeichen verwenden|Utilisez 4–128 caractères|Usa 4–128 caracteres|Folosește 4–128 de caractere|Используйте 4–128 символов|Usa 4–128 caratteri|Use 4–128 caracteres|Використовуйте 4–128 символів
Please wait|Poczekaj|Bitte warten|Veuillez patienter|Espera|Așteaptă|Подождите|Attendi|Aguarde|Зачекайте
Too many attempts. Try again in 30 seconds.|Zbyt wiele prób. Spróbuj za 30 sekund.|Zu viele Versuche. In 30 Sekunden erneut versuchen.|Trop de tentatives. Réessayez dans 30 secondes.|Demasiados intentos. Reintenta en 30 segundos.|Prea multe încercări. Reîncearcă în 30 de secunde.|Слишком много попыток. Повторите через 30 секунд.|Troppi tentativi. Riprova tra 30 secondi.|Muitas tentativas. Tente em 30 segundos.|Забагато спроб. Повторіть через 30 секунд.
Access configuration unavailable|Nie można odczytać ustawień dostępu|Zugriffskonfiguration nicht verfügbar|Configuration d’accès indisponible|Configuración de acceso no disponible|Configurarea accesului indisponibilă|Настройки доступа недоступны|Configurazione accesso non disponibile|Configuração de acesso indisponível|Налаштування доступу недоступні
Login required|Wymagane logowanie|Anmeldung erforderlich|Connexion requise|Inicio de sesión requerido|Autentificare necesară|Требуется вход|Accesso richiesto|Login necessário|Потрібен вхід
Local connections do not require a password|Połączenia lokalne nie wymagają hasła|Lokale Verbindungen benötigen kein Passwort|Les connexions locales ne nécessitent pas de mot de passe|Las conexiones locales no requieren contraseña|Conexiunile locale nu necesită parolă|Локальные подключения не требуют пароля|Le connessioni locali non richiedono password|Conexões locais não exigem senha|Локальні підключення не потребують пароля
Only the local operator can change access settings|Tylko lokalny operator może zmieniać dostęp|Nur lokale Bediener dürfen den Zugriff ändern|Seul l’opérateur local peut modifier les accès|Solo el operador local puede cambiar el acceso|Doar operatorul local poate schimba accesul|Только локальный оператор может менять доступ|Solo l’operatore locale può modificare l’accesso|Só o operador local pode alterar o acesso|Лише локальний оператор може змінювати доступ
Only the local operator can change the connection.|Tylko lokalny operator może zmieniać połączenie.|Nur lokale Bediener dürfen die Verbindung ändern.|Seul l’opérateur local peut modifier la connexion.|Solo el operador local puede cambiar la conexión.|Doar operatorul local poate schimba conexiunea.|Только локальный оператор может менять подключение.|Solo l’operatore locale può modificare la connessione.|Só o operador local pode alterar a conexão.|Лише локальний оператор може змінювати підключення.
Waiting for the local operator to connect.|Czekamy na połączenie lokalnego operatora.|Warte auf die Verbindung des lokalen Bedieners.|En attente de connexion de l’opérateur local.|Esperando la conexión del operador local.|Se așteaptă conexiunea operatorului local.|Ожидание подключения локального оператора.|In attesa della connessione dell’operatore locale.|Aguardando conexão do operador local.|Очікування підключення локального оператора.
Connection changed. Refresh the dashboard.|Połączenie zmieniło się. Odśwież panel.|Verbindung geändert. Dashboard aktualisieren.|Connexion modifiée. Actualisez le panneau.|La conexión cambió. Actualiza el panel.|Conexiunea s-a schimbat. Reîmprospătează panoul.|Подключение изменилось. Обновите панель.|Connessione modificata. Aggiorna il pannello.|A conexão mudou. Atualize o painel.|Підключення змінено. Оновіть панель.`;
