export const dynamicRows=`
Input pages|Strony inputów|Eingangsseiten|Pages des entrées|Páginas de entradas|Pagini de intrări|Страницы входов|Pagine ingressi|Páginas de entradas|Сторінки входів
Inputs per page|Inputy na stronę|Eingänge pro Seite|Entrées par page|Entradas por página|Intrări pe pagină|Входов на странице|Ingressi per pagina|Entradas por página|Входів на сторінці
{count} per page|{count} na stronę|{count} pro Seite|{count} par page|{count} por página|{count} pe pagină|{count} на странице|{count} per pagina|{count} por página|{count} на сторінці
Previous page|Poprzednia strona|Vorherige Seite|Page précédente|Página anterior|Pagina anterioară|Предыдущая страница|Pagina precedente|Página anterior|Попередня сторінка
Next page|Następna strona|Nächste Seite|Page suivante|Página siguiente|Pagina următoare|Следующая страница|Pagina successiva|Página seguinte|Наступна сторінка
Show on page|Pokaż na stronie|Auf Seite anzeigen|Afficher sur la page|Mostrar en la página|Arată pe pagină|Показать на странице|Mostra nella pagina|Mostrar na página|Показати на сторінці
Saved profile “{name}”.|Zapisano stanowisko „{name}”.|Profil „{name}” gespeichert.|Profil « {name} » enregistré.|Perfil «{name}» guardado.|Profilul „{name}” a fost salvat.|Профиль «{name}» сохранён.|Profilo «{name}» salvato.|Perfil «{name}» guardado.|Профіль «{name}» збережено.
Deleted “{name}”|Usunięto „{name}”|„{name}” gelöscht|« {name} » supprimé|«{name}» eliminado|„{name}” șters|«{name}» удалён|«{name}» eliminato|«{name}» eliminado|«{name}» видалено
{name} — copy|{name} — kopia|{name} — Kopie|{name} — copie|{name} — copia|{name} — copie|{name} — копия|{name} — copia|{name} — cópia|{name} — копія
Last read: {time}|Ostatni odczyt: {time}|Letzter Stand: {time}|Dernière lecture : {time}|Última lectura: {time}|Ultima citire: {time}|Последнее чтение: {time}|Ultima lettura: {time}|Última leitura: {time}|Останнє читання: {time}
{count} available|{count} dostępnych|{count} verfügbar|{count} disponibles|{count} disponibles|{count} disponibile|Доступно: {count}|{count} disponibili|{count} disponíveis|Доступно: {count}
 · {inputs} inputs · {mixes} mixes| · {inputs} inputów · {mixes} mixów| · {inputs} Eingänge · {mixes} Mixe| · {inputs} entrées · {mixes} mix| · {inputs} entradas · {mixes} mixes| · {inputs} intrări · {mixes} mixuri| · Входы: {inputs} · Миксы: {mixes}| · {inputs} ingressi · {mixes} mix| · {inputs} entradas · {mixes} mixes| · Входи: {inputs} · Мікси: {mixes}
Select mix: {name}|Wybierz mix: {name}|Mix wählen: {name}|Choisir le mix : {name}|Elegir mix: {name}|Alege mix: {name}|Выберите микс: {name}|Scegli mix: {name}|Escolher mix: {name}|Виберіть мікс: {name}
Show {name}|Pokaż {name}|{name} anzeigen|Afficher {name}|Mostrar {name}|Arată {name}|Показать {name}|Mostra {name}|Mostrar {name}|Показати {name}
Favorite: {name}|Ulubiony: {name}|Favorit: {name}|Favori : {name}|Favorito: {name}|Favorit: {name}|Избранное: {name}|Preferito: {name}|Favorito: {name}|Обране: {name}
Group for {name}|Grupa dla {name}|Gruppe für {name}|Groupe pour {name}|Grupo de {name}|Grup pentru {name}|Группа для {name}|Gruppo per {name}|Grupo de {name}|Група для {name}
Move {name} up|Przesuń {name} w górę|{name} nach oben|Monter {name}|Subir {name}|Mută {name} în sus|Переместить {name} вверх|Sposta {name} in alto|Mover {name} para cima|Перемістити {name} вгору
Move {name} down|Przesuń {name} w dół|{name} nach unten|Descendre {name}|Bajar {name}|Mută {name} în jos|Переместить {name} вниз|Sposta {name} in basso|Mover {name} para baixo|Перемістити {name} вниз
Rename {name}|Zmień nazwę {name}|{name} umbenennen|Renommer {name}|Renombrar {name}|Redenumește {name}|Переименовать {name}|Rinomina {name}|Mudar nome de {name}|Перейменувати {name}
Duplicate {name}|Duplikuj {name}|{name} duplizieren|Dupliquer {name}|Duplicar {name}|Duplică {name}|Дублировать {name}|Duplica {name}|Duplicar {name}|Дублювати {name}
Delete {name}|Usuń {name}|{name} löschen|Supprimer {name}|Eliminar {name}|Șterge {name}|Удалить {name}|Elimina {name}|Eliminar {name}|Видалити {name}
{ms} milliseconds|{ms} milisekund|{ms} Millisekunden|{ms} millisecondes|{ms} milisegundos|{ms} milisecunde|{ms} миллисекунд|{ms} millisecondi|{ms} milissegundos|{ms} мілісекунд
Inputs for {name}|Inputy dla {name}|Eingänge für {name}|Entrées pour {name}|Entradas para {name}|Intrări pentru {name}|Входы для {name}|Ingressi per {name}|Entradas para {name}|Входи для {name}
{source} to {mix}|{source} na {mix}|{source} auf {mix}|{source} vers {mix}|{source} a {mix}|{source} către {mix}|{source} на {mix}|{source} su {mix}|{source} para {mix}|{source} на {mix}
PROGRAM: {name}, immediate CUT|PROGRAM: {name}, natychmiastowy CUT|PROGRAM: {name}, sofortiger CUT|PROGRAM : {name}, CUT immédiat|PROGRAM: {name}, CUT inmediato|PROGRAM: {name}, CUT imediat|PROGRAM: {name}, мгновенный CUT|PROGRAM: {name}, CUT immediato|PROGRAM: {name}, CUT imediato|PROGRAM: {name}, миттєвий CUT
Confirmed|potwierdzono|Bestätigt|Confirmé|Confirmado|Confirmat|Подтверждено|Confermato|Confirmado|Підтверджено
Preview|podgląd|Vorschau|Aperçu|Vista previa|Previzualizare|Предпросмотр|Anteprima|Pré-visualização|Попередній перегляд
 (Stinger animation completion is not confirmed by XML)| (XML nie potwierdza końca animacji Stinger)| (XML bestätigt das Ende der Stinger-Animation nicht)| (La fin de l’animation Stinger n’est pas confirmée par XML)| (XML no confirma el final de la animación Stinger)| (XML nu confirmă sfârșitul animației Stinger)| (XML не подтверждает конец анимации Stinger)| (XML non conferma la fine dell’animazione Stinger)| (XML não confirma o fim da animação Stinger)| (XML не підтверджує кінець анімації Stinger)
Connected to {address}. Restart the dashboard server to change vMix.|Ten dashboard jest połączony z {address}. Użyj tego adresu. Aby zmienić komputer vMix, uruchom ponownie serwer dashboardu.|Mit {address} verbunden. Dashboard-Server zum Wechsel von vMix neu starten.|Connecté à {address}. Redémarrez le serveur du tableau de bord pour changer de vMix.|Conectado a {address}. Reinicia el servidor del panel para cambiar de vMix.|Conectat la {address}. Repornește serverul panoului pentru a schimba vMix.|Подключено к {address}. Перезапустите сервер панели для смены vMix.|Connesso a {address}. Riavvia il server del pannello per cambiare vMix.|Ligado a {address}. Reinicie o servidor do painel para mudar de vMix.|Підключено до {address}. Перезапустіть сервер панелі для зміни vMix.
vMix error {code}. Check input, mix and transition.|vMix zwrócił błąd {code}. Sprawdź input, mix i konfigurację przejścia.|vMix-Fehler {code}. Eingang, Mix und Übergang prüfen.|Erreur vMix {code}. Vérifiez entrée, mix et transition.|Error vMix {code}. Comprueba entrada, mix y transición.|Eroare vMix {code}. Verifică intrarea, mixul și tranziția.|Ошибка vMix {code}. Проверьте вход, микс и переход.|Errore vMix {code}. Controlla ingresso, mix e transizione.|Erro vMix {code}. Verifique entrada, mix e transição.|Помилка vMix {code}. Перевірте вхід, мікс і перехід.
Cannot read vMix. {detail}|Nie można odczytać vMix. {detail}|vMix kann nicht gelesen werden. {detail}|Impossible de lire vMix. {detail}|No se puede leer vMix. {detail}|Nu se poate citi vMix. {detail}|Не удалось прочитать vMix. {detail}|Impossibile leggere vMix. {detail}|Não foi possível ler o vMix. {detail}|Не вдалося прочитати vMix. {detail}
Example: AUX 1 — graphics|np. Wóz 1 — grafika|Beispiel: AUX 1 — Grafik|Exemple : AUX 1 — graphisme|Ejemplo: AUX 1 — gráficos|Exemplu: AUX 1 — grafică|Пример: AUX 1 — графика|Esempio: AUX 1 — grafica|Exemplo: AUX 1 — gráficos|Приклад: AUX 1 — графіка
Group, e.g. Graphics|Grupa, np. Plansze|Gruppe, z. B. Grafik|Groupe, ex. Graphisme|Grupo, p. ej. Gráficos|Grup, de ex. Grafică|Группа, например Графика|Gruppo, es. Grafica|Grupo, ex. Gráficos|Група, наприклад Графіка
`;
