export const messageRows=`
Duration must be 1–10000 ms.|Podaj czas od 1 do 10000 ms.|Dauer muss 1–10000 ms betragen.|La durée doit être de 1 à 10000 ms.|La duración debe ser de 1 a 10000 ms.|Durata trebuie să fie 1–10000 ms.|Длительность: 1–10000 мс.|La durata deve essere 1–10000 ms.|A duração deve ser de 1 a 10000 ms.|Тривалість: 1–10000 мс.
Waiting for confirmation from vMix…|Czekam na potwierdzenie z vMix…|Warte auf Bestätigung von vMix…|En attente de confirmation de vMix…|Esperando confirmación de vMix…|Se așteaptă confirmarea vMix…|Ожидание подтверждения vMix…|In attesa di conferma da vMix…|A aguardar confirmação do vMix…|Очікування підтвердження vMix…
Could not connect to vMix.|Brak połączenia z vMix.|Keine Verbindung zu vMix.|Connexion à vMix impossible.|No se pudo conectar a vMix.|Conexiunea la vMix a eșuat.|Не удалось подключиться к vMix.|Impossibile connettersi a vMix.|Não foi possível ligar ao vMix.|Не вдалося підключитися до vMix.
Invalid vMix response. Check IP and port.|Adres nie zwrócił danych vMix. Sprawdź IP i port.|Ungültige vMix-Antwort. IP und Port prüfen.|Réponse vMix invalide. Vérifiez IP et port.|Respuesta vMix no válida. Comprueba IP y puerto.|Răspuns vMix invalid. Verifică IP-ul și portul.|Неверный ответ vMix. Проверьте IP и порт.|Risposta vMix non valida. Verifica IP e porta.|Resposta vMix inválida. Verifique IP e porta.|Некоректна відповідь vMix. Перевірте IP і порт.
Could not save browser settings.|Nie udało się zapisać ustawień stanowiska.|Browsereinstellungen konnten nicht gespeichert werden.|Impossible d’enregistrer les paramètres locaux.|No se pudieron guardar los ajustes locales.|Nu s-au putut salva setările locale.|Не удалось сохранить настройки браузера.|Impossibile salvare le impostazioni locali.|Não foi possível guardar as definições locais.|Не вдалося зберегти налаштування браузера.
Maximum 30 profiles.|Limit: 30 profili.|Maximal 30 Profile.|30 profils maximum.|Máximo 30 perfiles.|Maximum 30 de profiluri.|Не более 30 профилей.|Massimo 30 profili.|Máximo de 30 perfis.|Не більше 30 профілів.
Could not save profile.|Nie udało się zapisać profilu.|Profil konnte nicht gespeichert werden.|Impossible d’enregistrer le profil.|No se pudo guardar el perfil.|Profilul nu a putut fi salvat.|Не удалось сохранить профиль.|Impossibile salvare il profilo.|Não foi possível guardar o perfil.|Не вдалося зберегти профіль.
Station link copied.|Skopiowano link stanowiska.|Arbeitsplatz-Link kopiert.|Lien du poste copié.|Enlace del puesto copiado.|Linkul postului a fost copiat.|Ссылка рабочего места скопирована.|Link postazione copiato.|Ligação do posto copiada.|Посилання робочого місця скопійовано.
Select and copy the station link.|Zaznacz i skopiuj link z pola stanowiska.|Arbeitsplatz-Link markieren und kopieren.|Sélectionnez et copiez le lien du poste.|Selecciona y copia el enlace del puesto.|Selectează și copiază linkul postului.|Выделите и скопируйте ссылку рабочего места.|Seleziona e copia il link postazione.|Selecione e copie a ligação do posto.|Виділіть і скопіюйте посилання робочого місця.
Could not create station link.|Nie udało się przygotować linku.|Arbeitsplatz-Link konnte nicht erstellt werden.|Impossible de créer le lien du poste.|No se pudo crear el enlace del puesto.|Linkul postului nu a putut fi creat.|Не удалось создать ссылку рабочего места.|Impossibile creare il link postazione.|Não foi possível criar a ligação do posto.|Не вдалося створити посилання робочого місця.
Could not load station. Select a profile or connect manually.|Nie udało się wczytać stanowiska. Wybierz profil lub połącz się ręcznie.|Arbeitsplatz nicht geladen. Profil wählen oder manuell verbinden.|Poste non chargé. Choisissez un profil ou connectez-vous manuellement.|No se cargó el puesto. Elige un perfil o conecta manualmente.|Postul nu a fost încărcat. Alege un profil sau conectează manual.|Не удалось загрузить рабочее место. Выберите профиль или подключитесь вручную.|Postazione non caricata. Scegli un profilo o connettiti manualmente.|Posto não carregado. Escolha um perfil ou ligue manualmente.|Не вдалося завантажити робоче місце. Виберіть профіль або підключіться вручну.
Full screen is unavailable in this browser.|Pełny ekran jest niedostępny w tej przeglądarce.|Vollbild ist in diesem Browser nicht verfügbar.|Le plein écran est indisponible dans ce navigateur.|Pantalla completa no disponible en este navegador.|Ecranul complet nu este disponibil în acest browser.|Полный экран недоступен в этом браузере.|Schermo intero non disponibile in questo browser.|Ecrã inteiro indisponível neste navegador.|Повний екран недоступний у цьому браузері.
Mix unavailable. Select another or wait for it to return.|Mix niedostępny. Wybierz inny lub poczekaj na jego powrót.|Mix nicht verfügbar. Anderen wählen oder warten.|Mix indisponible. Choisissez-en un autre ou attendez son retour.|Mix no disponible. Elige otro o espera su regreso.|Mix indisponibil. Alege altul sau așteaptă să revină.|Микс недоступен. Выберите другой или дождитесь его возврата.|Mix non disponibile. Scegli un altro o attendi il ritorno.|Mix indisponível. Escolha outro ou aguarde o regresso.|Мікс недоступний. Виберіть інший або дочекайтеся його повернення.
Enable sources in Station → Input layout.|Otwórz „Stanowisko” → „Układ inputów” i włącz źródła.|Quellen unter Arbeitsplatz → Eingangslayout aktivieren.|Activez les sources dans Poste → Disposition des entrées.|Activa fuentes en Puesto → Diseño de entradas.|Activează sursele în Post de lucru → Aranjare intrări.|Включите источники в Рабочее место → Расположение входов.|Abilita sorgenti in Postazione → Disposizione ingressi.|Ative fontes em Posto → Disposição das entradas.|Увімкніть джерела в Робоче місце → Розташування входів.
Add inputs in vMix. They appear automatically.|Dodaj inputy w vMix. Pojawią się tutaj automatycznie.|Eingänge in vMix hinzufügen. Sie erscheinen automatisch.|Ajoutez des entrées dans vMix. Elles apparaîtront automatiquement.|Añade entradas en vMix. Aparecerán automáticamente.|Adaugă intrări în vMix. Vor apărea automat.|Добавьте входы в vMix. Они появятся автоматически.|Aggiungi ingressi in vMix. Appariranno automaticamente.|Adicione entradas no vMix. Aparecerão automaticamente.|Додайте входи у vMix. Вони з’являться автоматично.
Enter the vMix address to load inputs and mixes.|Wpisz adres komputera powyżej. Inputy i dostępne mixy zostaną pobrane automatycznie.|vMix-Adresse eingeben, um Eingänge und Mixe zu laden.|Saisissez l’adresse vMix pour charger les entrées et mix.|Introduce la dirección de vMix para cargar entradas y mixes.|Introdu adresa vMix pentru a încărca intrările și mixurile.|Введите адрес vMix для загрузки входов и миксов.|Inserisci l’indirizzo vMix per caricare ingressi e mix.|Introduza o endereço vMix para carregar entradas e mixes.|Введіть адресу vMix для завантаження входів і міксів.
This link contains a copy of the profile.|Link zawiera kopię bieżącego profilu. Otwórz go na urządzeniu operatora.|Dieser Link enthält eine Kopie des Profils.|Ce lien contient une copie du profil.|Este enlace contiene una copia del perfil.|Acest link conține o copie a profilului.|Ссылка содержит копию профиля.|Questo link contiene una copia del profilo.|Esta ligação contém uma cópia do perfil.|Посилання містить копію профілю.
Use the dashboard LAN address when sharing links.|Udostępniając link, używaj adresu LAN dashboardu zamiast localhost.|Beim Teilen die LAN-Adresse des Dashboards verwenden.|Utilisez l’adresse LAN du tableau de bord pour partager.|Usa la dirección LAN del panel al compartir enlaces.|Folosește adresa LAN a panoului când distribui linkuri.|Для обмена ссылками используйте LAN-адрес панели.|Usa l’indirizzo LAN del pannello per condividere link.|Use o endereço LAN do painel ao partilhar ligações.|Для поширення посилань використовуйте LAN-адресу панелі.
Set visibility, favorites and groups. Arrows reorder within groups.|Zmień widoczność, oznacz ulubione i wpisz nazwy grup. Strzałki zmieniają kolejność wewnątrz grup.|Sichtbarkeit, Favoriten und Gruppen festlegen. Pfeile sortieren innerhalb der Gruppen.|Réglez visibilité, favoris et groupes. Les flèches réordonnent les groupes.|Configura visibilidad, favoritos y grupos. Las flechas reordenan dentro de cada grupo.|Setează vizibilitatea, favoritele și grupurile. Săgețile reordonează în grup.|Настройте видимость, избранное и группы. Стрелки меняют порядок внутри групп.|Imposta visibilità, preferiti e gruppi. Le frecce riordinano nei gruppi.|Defina visibilidade, favoritos e grupos. As setas ordenam dentro dos grupos.|Налаштуйте видимість, обране та групи. Стрілки змінюють порядок у групах.
Changes save locally. Save profile keeps a separate preset.|Bieżące ustawienia zapisują się lokalnie. „Zapisz profil” zachowuje osobny preset.|Änderungen werden lokal gespeichert. Profil speichern sichert eine separate Vorlage.|Les changements sont locaux. Enregistrer le profil conserve un préréglage distinct.|Los cambios se guardan localmente. Guardar perfil conserva un preset separado.|Modificările se salvează local. Salvează profilul păstrează un preset separat.|Изменения сохраняются локально. Сохранить профиль создаёт отдельный пресет.|Le modifiche sono locali. Salva profilo conserva un preset separato.|As alterações são locais. Guardar perfil mantém uma predefinição separada.|Зміни зберігаються локально. Зберегти профіль створює окремий пресет.
File is too large.|Plik jest zbyt duży.|Datei ist zu groß.|Fichier trop volumineux.|El archivo es demasiado grande.|Fișierul este prea mare.|Файл слишком большой.|File troppo grande.|Ficheiro demasiado grande.|Файл завеликий.
Profiles imported.|Zaimportowano profile.|Profile importiert.|Profils importés.|Perfiles importados.|Profiluri importate.|Профили импортированы.|Profili importati.|Perfis importados.|Профілі імпортовано.
Could not read file.|Nie udało się odczytać pliku.|Datei konnte nicht gelesen werden.|Impossible de lire le fichier.|No se pudo leer el archivo.|Fișierul nu a putut fi citit.|Не удалось прочитать файл.|Impossibile leggere il file.|Não foi possível ler o ficheiro.|Не вдалося прочитати файл.
Invalid profile.|Nieprawidłowy profil stanowiska.|Ungültiges Profil.|Profil invalide.|Perfil no válido.|Profil invalid.|Недопустимый профиль.|Profilo non valido.|Perfil inválido.|Некоректний профіль.
Invalid station address.|Nieprawidłowy adres stanowiska.|Ungültige Arbeitsplatzadresse.|Adresse du poste invalide.|Dirección del puesto no válida.|Adresă de post invalidă.|Недопустимый адрес рабочего места.|Indirizzo postazione non valido.|Endereço do posto inválido.|Некоректна адреса робочого місця.
Profile requires a local vMix address.|Profil wymaga lokalnego adresu vMix.|Profil benötigt eine lokale vMix-Adresse.|Le profil nécessite une adresse vMix locale.|El perfil requiere una dirección local de vMix.|Profilul necesită o adresă locală vMix.|Профилю нужен локальный адрес vMix.|Il profilo richiede un indirizzo vMix locale.|O perfil exige um endereço local do vMix.|Профіль потребує локальної адреси vMix.
Invalid input layout.|Nieprawidłowy układ stanowiska.|Ungültiges Eingangslayout.|Disposition des entrées invalide.|Diseño de entradas no válido.|Aranjare intrări invalidă.|Недопустимое расположение входов.|Disposizione ingressi non valida.|Disposição das entradas inválida.|Некоректне розташування входів.
Profile name already exists.|Ta nazwa profilu już istnieje.|Profilname bereits vorhanden.|Ce nom de profil existe déjà.|El nombre del perfil ya existe.|Numele profilului există deja.|Такое имя профиля уже есть.|Nome profilo già esistente.|O nome do perfil já existe.|Така назва профілю вже існує.
Unsupported profile file.|Nieobsługiwany plik profili.|Nicht unterstützte Profildatei.|Fichier de profils non pris en charge.|Archivo de perfiles no compatible.|Fișier de profiluri incompatibil.|Неподдерживаемый файл профилей.|File profili non supportato.|Ficheiro de perfis não suportado.|Непідтримуваний файл профілів.
Enter a local IPv4 address, e.g. 192.168.1.100:8088.|Podaj lokalny adres IPv4, np. 192.168.1.100:8088, bez hasła i parametrów.|Lokale IPv4-Adresse eingeben, z. B. 192.168.1.100:8088.|Saisissez une adresse IPv4 locale, ex. 192.168.1.100:8088.|Introduce una dirección IPv4 local, p. ej. 192.168.1.100:8088.|Introdu o adresă IPv4 locală, de ex. 192.168.1.100:8088.|Введите локальный IPv4-адрес, например 192.168.1.100:8088.|Inserisci un indirizzo IPv4 locale, es. 192.168.1.100:8088.|Introduza um endereço IPv4 local, ex. 192.168.1.100:8088.|Введіть локальну IPv4-адресу, наприклад 192.168.1.100:8088.
Invalid request.|Nieprawidłowe żądanie.|Ungültige Anfrage.|Requête invalide.|Solicitud no válida.|Cerere invalidă.|Недопустимый запрос.|Richiesta non valida.|Pedido inválido.|Некоректний запит.
Another operator is using this mix. Wait for completion.|Ten mix wykonuje polecenie innego operatora. Poczekaj na zakończenie.|Ein anderer Operator nutzt diesen Mix. Abschluss abwarten.|Un autre opérateur utilise ce mix. Attendez la fin.|Otro operador está usando este mix. Espera a que termine.|Alt operator folosește acest mix. Așteaptă finalizarea.|Другой оператор использует этот микс. Дождитесь завершения.|Un altro operatore usa questo mix. Attendi il termine.|Outro operador usa este mix. Aguarde a conclusão.|Інший оператор використовує цей мікс. Дочекайтеся завершення.
Mix assignment changed. Refresh and select it again.|Zmieniło się przypisanie mixu. Odśwież panel i wybierz go ponownie.|Mix-Zuordnung geändert. Aktualisieren und erneut wählen.|L’affectation du mix a changé. Actualisez et sélectionnez à nouveau.|La asignación del mix cambió. Actualiza y selecciona de nuevo.|Alocarea mixului s-a schimbat. Actualizează și selectează din nou.|Назначение микса изменилось. Обновите и выберите снова.|Assegnazione mix cambiata. Aggiorna e seleziona di nuovo.|A atribuição do mix mudou. Atualize e selecione novamente.|Призначення міксу змінилося. Оновіть і виберіть знову.
This input is no longer available.|Ten input nie jest już dostępny w vMix.|Dieser Eingang ist nicht mehr verfügbar.|Cette entrée n’est plus disponible.|Esta entrada ya no está disponible.|Această intrare nu mai este disponibilă.|Этот вход больше недоступен.|Questo ingresso non è più disponibile.|Esta entrada já não está disponível.|Цей вхід більше недоступний.
Cannot route a mix to itself.|Nie można wysłać mixu na niego samego.|Ein Mix kann nicht auf sich selbst geroutet werden.|Impossible d’envoyer un mix vers lui-même.|No se puede enviar un mix a sí mismo.|Un mix nu poate fi trimis către el însuși.|Нельзя направить микс на самого себя.|Impossibile inviare un mix a sé stesso.|Não é possível enviar um mix para si próprio.|Не можна спрямувати мікс на самого себе.
Preview changed. Check PREVIEW before taking.|Podgląd zmienił się. Sprawdź PREVIEW i ponów przejście.|Vorschau geändert. PREVIEW vor dem Übergang prüfen.|L’aperçu a changé. Vérifiez PREVIEW avant la transition.|La vista previa cambió. Revisa PREVIEW antes de la transición.|Previzualizarea s-a schimbat. Verifică PREVIEW înainte de tranziție.|Предпросмотр изменился. Проверьте PREVIEW перед переходом.|Anteprima cambiata. Controlla PREVIEW prima della transizione.|A pré-visualização mudou. Verifique PREVIEW antes da transição.|Попередній перегляд змінився. Перевірте PREVIEW перед переходом.
Source switched, but playback was not confirmed.|Źródło przełączono, ale vMix nie potwierdził odtwarzania.|Quelle umgeschaltet, Wiedergabe aber nicht bestätigt.|Source commutée, mais lecture non confirmée.|Fuente cambiada, pero reproducción no confirmada.|Sursa a fost comutată, dar redarea nu a fost confirmată.|Источник переключён, но воспроизведение не подтверждено.|Sorgente commutata, riproduzione non confermata.|Fonte alterada, mas reprodução não confirmada.|Джерело перемкнуто, але відтворення не підтверджено.
Mix configuration changed during the command. Check vMix.|Konfiguracja mixów zmieniła się podczas polecenia. Sprawdź program w vMix.|Mix-Konfiguration während des Befehls geändert. vMix prüfen.|Configuration des mix modifiée pendant la commande. Vérifiez vMix.|La configuración cambió durante el comando. Comprueba vMix.|Configurația mixurilor s-a schimbat în timpul comenzii. Verifică vMix.|Конфигурация изменилась во время команды. Проверьте vMix.|Configurazione cambiata durante il comando. Controlla vMix.|A configuração mudou durante o comando. Verifique o vMix.|Конфігурація змінилася під час команди. Перевірте vMix.
Command sent but not confirmed. Check vMix before retrying.|Wysłano polecenie, ale nie potwierdzono docelowego źródła. Sprawdź vMix przed kolejnym kliknięciem.|Befehl gesendet, aber nicht bestätigt. Vor erneutem Versuch vMix prüfen.|Commande envoyée mais non confirmée. Vérifiez vMix avant de réessayer.|Comando enviado sin confirmar. Comprueba vMix antes de reintentar.|Comandă trimisă, dar neconfirmată. Verifică vMix înainte de a reîncerca.|Команда отправлена, но не подтверждена. Проверьте vMix перед повтором.|Comando inviato ma non confermato. Controlla vMix prima di riprovare.|Comando enviado mas não confirmado. Verifique o vMix antes de repetir.|Команду надіслано, але не підтверджено. Перевірте vMix перед повтором.
Result uncertain. Check vMix. Command was not retried.|Wynik polecenia jest niepewny. Sprawdź program w vMix. Polecenie nie zostało ponowione.|Ergebnis unklar. vMix prüfen. Befehl wurde nicht wiederholt.|Résultat incertain. Vérifiez vMix. Commande non répétée.|Resultado incierto. Comprueba vMix. No se repitió el comando.|Rezultat incert. Verifică vMix. Comanda nu a fost repetată.|Результат неизвестен. Проверьте vMix. Команда не повторялась.|Risultato incerto. Controlla vMix. Comando non ripetuto.|Resultado incerto. Verifique o vMix. O comando não foi repetido.|Результат невідомий. Перевірте vMix. Команда не повторювалася.
Unsupported transition.|Nieobsługiwane przejście.|Nicht unterstützter Übergang.|Transition non prise en charge.|Transición no compatible.|Tranziție incompatibilă.|Неподдерживаемый переход.|Transizione non supportata.|Transição não suportada.|Непідтримуваний перехід.
`;
export const aliases:Record<string,string>={
'Nie udało się zapisać układu w przeglądarce.':'Nie udało się zapisać ustawień stanowiska.',
'Nie udało się zapisać profili.':'Nie udało się zapisać profilu.',
'Można zapisać do 30 profili. Użyj nazwy istniejącego profilu, aby go zastąpić.':'Limit: 30 profili.',
'Nieprawidłowa lista inputów.':'Nieprawidłowy układ stanowiska.',
'Link stanowiska jest zbyt długi.':'Plik jest zbyt duży.',
'Podaj adres IP komputera z vMix.':'Podaj lokalny adres IPv4, np. 192.168.1.100:8088, bez hasła i parametrów.',
'Nieprawidłowa operacja.':'Nieprawidłowe żądanie.',
'Wymagany JSON.':'Nieprawidłowe żądanie.',
'Niedozwolone źródło żądania.':'Nieprawidłowe żądanie.',
'Zbyt duże żądanie.':'Nieprawidłowe żądanie.',
'Nieprawidłowy input lub identyfikator mixu. Odśwież panel.':'Zmieniło się przypisanie mixu. Odśwież panel i wybierz go ponownie.',
'Czas przejścia musi wynosić od 1 do 10000 ms.':'Podaj czas od 1 do 10000 ms.',
'Czas: 1–10000 ms':'Podaj czas od 1 do 10000 ms.',
'Nieprawidłowa odpowiedź XML z vMix.':'Adres nie zwrócił danych vMix. Sprawdź IP i port.',
'Brak listy inputów w odpowiedzi vMix.':'Adres nie zwrócił danych vMix. Sprawdź IP i port.',
'Nieprawidłowy input w odpowiedzi vMix.':'Adres nie zwrócił danych vMix. Sprawdź IP i port.',
'Nie udało się potwierdzić przełączenia. Sprawdź vMix.':'Wynik polecenia jest niepewny. Sprawdź program w vMix. Polecenie nie zostało ponowione.'
};
