import { readFile, writeFile, copyFile, mkdir } from 'node:fs/promises';
import ts from 'typescript';
await mkdir('dist/windows', { recursive: true });
await writeFile('dist/windows/vmix-proxy.mjs', ts.transpileModule(await readFile('lib/vmix-proxy.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll(".ts'", ".mjs'"));
await copyFile('portable/server.mjs','dist/windows/server.mjs');
await writeFile('dist/windows/START-WINDOWS.bat', '@echo off\r\ncd /d "%~dp0"\r\nwhere node >nul 2>nul\r\nif errorlevel 1 (\r\n echo Zainstaluj Node.js 22.13 lub nowszy.\r\n pause\r\n exit /b 1\r\n)\r\necho Otworz http://127.0.0.1:3000 gdy pojawi sie komunikat gotowosci.\r\nnode server.mjs\r\npause\r\n');
await writeFile('dist/windows/INSTRUKCJA.txt', '1. Zamknij poprzedni dashboard (Ctrl+C w jego oknie).\r\n2. Rozpakuj caly ZIP do nowego folderu.\r\n3. Uruchom START-WINDOWS.bat. Wymagany Node.js 22.13 lub nowszy. Nie trzeba npm install.\r\n4. Po komunikacie gotowosci otworz http://127.0.0.1:3000 i nacisnij Ctrl+F5.\r\n5. Wpisz adres vMix, np. 127.0.0.1:8088 na tym samym komputerze, i kliknij Polacz.\r\nDostep LAN: node server.mjs --lan. Uzywaj w zaufanej sieci; panel nie ma logowania.\r\n');
await writeFile('dist/windows/START-LAN.bat', (await readFile('dist/windows/START-WINDOWS.bat','utf8')).replace('node server.mjs','node server.mjs --lan'));
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWIELU OPERATOROW\r\nUruchom START-LAN.bat na jednym komputerze. Konsola poda adres LAN dla pozostalych osob.\r\nZezwol Node.js na ruch w sieci prywatnej w zaporze Windows.\r\nKazdy otwiera ten adres na swoim urzadzeniu, laczy sie z tym samym vMix i wybiera Moj mix.\r\nWybor jest zapamietywany osobno w kazdej przegladarce. Nie wymaga osobnych serwerow.\r\nMoj mix filtruje karty oraz przyciski. Nie rezerwuje mixu ani nie blokuje go innym osobom.\r\nNiedostepne mixy sa ukryte; znikniecie wybranego mixu nie wybiera automatycznie innego.\r\nNazwy pochodza z inputow typu Mix, w kolejnosci vMix.\r\n', {flag:'a'});

await writeFile('dist/windows/transitions.mjs', ts.transpileModule(await readFile('lib/transitions.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);

await writeFile('dist/windows/vmix-xml.mjs', ts.transpileModule(await readFile('lib/vmix-xml.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll(".ts'", ".mjs'"));
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 5.0\r\nUstawienia polaczenia sa zwijane po polaczeniu; przycisk Ustawienia otwiera je ponownie.\r\nCut/Fade i presety czasu sa dostepne nad inputami.\r\nSerwer blokuje jednoczesne polecenia na ten sam mix tylko na czas operacji. Inne mixy pracuja niezaleznie.\r\nWszyscy operatorzy musza korzystac z tego samego uruchomionego serwera dashboardu. Nie jest to rezerwacja stanowiska ani logowanie.\r\nPolecenia wymagaja potwierdzenia z XML. Przy niepewnym wyniku sprawdz vMix; panel nie ponawia polecen automatycznie.\r\nStinger: potwierdzane jest zrodlo na programie. XML nie potwierdza konca animacji; minimalna blokada wynosi 2 sekundy.\r\nNie mieszaj wersji panelu: po aktualizacji wszyscy operatorzy powinni odswiezyc strone Ctrl+F5.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 6.0 - STANOWISKA\r\n1. Polacz sie z vMix i wybierz jeden mix.\r\n2. Wpisz nazwe stanowiska. W Uklad inputow ustaw widocznosc, ulubione, grupy i kolejnosc.\r\n3. Wybierz wielkosc kafelkow, efekt i czas. Kliknij Zapisz profil.\r\n4. Link stanowiska tworzy kopie tych ustawien; otwarcie go automatycznie laczy panel z vMix. Nie wykonuje przelaczenia.\r\n5. Generuj link z panelu otwartego pod adresem LAN serwera, aby dzialal na innym urzadzeniu. W razie braku dostepu do schowka skopiuj link z pola.\r\nProfile i uklady sa zapisane w przegladarce, nie na serwerze. Link jest kopia, a nie wspolnie edytowanym profilem.\r\nPo zmianach zapisz profil ponownie i wygeneruj nowy link. Usuniecie danych przegladarki usuwa lokalne profile.\r\nOstatni zapisany lub wczytany profil jest przywracany po otwarciu strony. Zmiana mixu recznie wylacza to przywracanie.\r\nAktualizuj: zamknij poprzedni serwer, rozpakuj ZIP do nowego folderu, uruchom START-LAN.bat i odswiez wszystkie przegladarki Ctrl+F5.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 7.0 - MATRYCA ZRODEL\r\nNaglowki i przyciski maja wspolne, stale szerokosci kolumn. Aktywne zrodlo oznacza jasny przycisk PROGRAM.\r\nProfile i edytor inputow sa dostepne pod przyciskiem Stanowisko w gornym pasku.\r\nNaglowek tabeli pozostaje widoczny podczas przewijania listy. Na malym ekranie matryce mozna przewijac poziomo.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 9.0 - NAPRAWY\r\nPierwsze udane polaczenie wybiera jedna instancje vMix dla uruchomionego serwera dashboardu.\r\nAdresy localhost, 127.0.0.1 oraz IPv4 tego komputera sa rozpoznawane jako lokalne aliasy i wspoldziela blokady.\r\nInny komputer vMix jest odrzucany. Aby zmienic instancje, zatrzymaj i uruchom ponownie dashboard.\r\nLink stanowiska importuje sie jeden raz i znika z adresu po udanym zapisie lokalnym.\r\nBiezace ustawienia nazwanego stanowiska zapisuja sie automatycznie; Zapisz profil zapisuje osobny preset.\r\nKomunikaty operacji sa widoczne nad dolna krawedzia ekranu.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 10 - ZRODLA I PROFILE\r\nWyszukiwarka filtruje po nazwie, numerze i typie. Dostepne filtry grup i ulubionych.\r\nFiltry nie zmieniaja aktywnego programu i zeruja sie po zmianie mixu.\r\nStanowisko > Profile: zmiana nazwy, duplikowanie, usuwanie z Cofnij, eksport i import JSON.\r\nImport zachowuje istniejace profile. Powtarzajace sie nazwy otrzymuja numer; limit 30 profili.\r\nUsuniecie presetu nie wylacza biezacego stanowiska. Dane sa lokalne w przegladarce.\r\n', {flag:'a'});
await writeFile('dist/windows/vmix-demo.mjs', ts.transpileModule(await readFile('lib/vmix-demo.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll(".ts'", ".mjs'"));
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 11 - DEMO\r\nUstawienia > Uruchom demo. Nie wymaga vMix ani osobnego emulatora.\r\n12 inputow, 4 mixy; Mix 5 pozostaje niedostepny. Demo symuluje program, czas przejscia i Play, bez obrazu wideo.\r\nOperatorzy tego samego serwera wspoldziela stan demo; kazdy wybiera swoj mix.\r\nDemo dziala w pamieci i resetuje sie po restarcie serwera. Zakoncz demo wraca do ustawien polaczenia.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 11.1\r\nPoprawiono obsluge zadania demo w serwerze podgladu.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 11.2\r\nStyle demo, wyszukiwania i profili sa ladowane razem z panelem z osobnego arkusza CSS.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 12 - REALIZATOR\r\nWybierz pojedynczy mix i kliknij Realizator.\r\nCzerwony rzad PROGRAM przelacza natychmiast (CUT). Zielony PREVIEW wybiera podglad.\r\nCUT przenosi podglad na program natychmiast; AUTO stosuje wybrany efekt i czas.\r\nPREVIEW jest odczytywany z vMix, wspolny dla operatorow mixu. Zmieniony podglad powoduje odrzucenie nieaktualnego polecenia AUTO/CUT.\r\nDemo obsluguje oba rzedy. Pulpit pokazuje nazwy i stan, nie obraz wideo.\r\nT-Bar nie jest obslugiwany przez dodatkowe mixy vMix.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 12.1\r\nPrzebudowano wyglad realizatora: matowe przyciski, subtelne kolory programu i podgladu, zwarty panel przejsc.\r\n', {flag:'a'});

await writeFile('dist/windows/vmix-limits.mjs', ts.transpileModule(await readFile('lib/vmix-limits.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 13 - MIX 1-16\r\nObsluga programu glownego i 15 dodatkowych mixow. Panel pokazuje tylko mixy dostepne w polaczonym vMix.\r\nPREVIEW, CUT, AUTO i profile obsluguja caly zakres.\r\nPrzy wielu mixach karty i matryca przewijaja sie poziomo; nazwy zrodel pozostaja widoczne.\r\nDemo ma teraz 16 mixow oraz 24 inputy.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nWERSJA 13.2\r\nNowy wybor mixa z wyszukiwaniem po nazwie lub numerze i przewijana lista.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 14 - LANGUAGES\r\nSettings > Language: EN (default), PL, DE, FR, ES, RO, RU, IT, PT, UK.\r\nLanguage is saved per browser and changes without reconnecting to vMix. Source names and user profiles are preserved.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 15 - SETTINGS DIALOG\r\nSettings opens automatically at startup with a dimmed background. Enter the vMix IP or start demo.\r\nThe dialog closes after a successful connection. Settings opens it again. Connection errors appear inside the dialog.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 16 - DIRECTOR PAGES\r\nPROGRAM and PREVIEW share pages of 12 inputs (options: 12/24/48). Search covers all inputs.\r\nTop readouts and CUT/AUTO remain independent of the selected page. Use the locate icon to find the active source on another page.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 16.1\r\nSwitcher is the first and default single-mix view; Sources is second. Your next view choice is saved locally.\r\nThe header uses a compact VMIX/DEMO/OFFLINE badge. Hover for connection details.\r\n', {flag:'a'});
await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 17 - GLOBAL TILE SIZE\r\nSettings > Tile size controls Sources, Switcher keys and matrix density. It is saved per browser and overrides profile sizes once selected.\r\nThe size control has moved from Station to Settings. Source toolbar edges now align with the tile grid.\r\n', {flag:'a'});

await writeFile('dist/windows/operator-presence.mjs', ts.transpileModule(await readFile('lib/operator-presence.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll(".ts'", ".mjs'"));

await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 18 - OPERATOR TOOLS\r\nSwitcher: 1-9 / 0 / - / = select PREVIEW slots 1-12 on the current page. Enter AUTO; C CUT. Disabled while typing or a dialog is open. Settings can disable shortcuts.\r\nON AIR locks local configuration, not access for other operators. It does not start streaming.\r\nStation > Operator sets your shared presence name. Presence expires after 20 seconds. Use one LAN server for all operators.\r\nBack returns by CUT to the previous observed program source, with stale-program protection.\r\nFocus hides additional panels. Exit focus remains available.\r\nStation > Input layout: drag handles reorder inputs; dropping into another group adopts that group and favorite status. Arrow buttons remain available. Save profile preserves a named preset.\r\n', {flag:'a'});

await writeFile('dist/windows/access-control.mjs', ts.transpileModule(await readFile('lib/access-control.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText.replaceAll(".ts'", ".mjs'"));

await writeFile('dist/windows/local-access.mjs', ts.transpileModule(await readFile('lib/local-access.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);

await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 19 - PASSWORD ACCESS\r\nSettings > Password protection: enter and confirm 4-128 characters, then Save access settings.\r\nLocalhost / loopback connections bypass the password. LAN connections require login.\r\nPassword changes log out other sessions. Sessions expire after 8 hours or server restart.\r\nProtection is saved as a salted hash in .vmix-access.json in the server working folder. Copy this file when moving to a new version folder. It is never included in the release ZIP.\r\nThe local operator can change or disable protection without the old password.\r\nUse direct LAN access, not a loopback reverse proxy (which would appear local).\r\n', {flag:'a'});

await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 19.4 - LOCAL ADMINISTRATOR\r\nOnly localhost / loopback can configure the vMix IP, start demo or manage the password.\r\nLAN operators log in and automatically join the server connection; their mix and layout stay independent.\r\nIf the local operator has not connected yet, LAN clients wait and join automatically when ready.\r\nOpen http://127.0.0.1:3000 on the server computer for administration.\r\n', {flag:'a'});

await writeFile('dist/windows/program-controls.mjs', ts.transpileModule(await readFile('lib/program-controls.ts','utf8'), {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);

await writeFile('dist/windows/INSTRUKCJA.txt', '\r\nVERSION 19.5 - PGM CONTROLS\r\nSelect PGM > Switcher for stinger selectors, shared overlay IN/OUT, FTB and REC/STREAM/EXT status.\r\nSelect a stinger then press AUTO; configure its animation in vMix. Overlay OUT clears the shared channel.\r\nFTB activation requires a second click; Restore PGM restores output. Demo simulates state only, without video.\r\n', {flag:'a'});
